CREATE DATABASE Ecommerce;

CREATE TABLE product_category(
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE,
    desc TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)
CREATE TABLE product_inventory(
    id INT AUTO_INCREMENT PRIMARY KEY,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)
CREATE TABLE discount(
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE,
    desc TEXT NOT NULL,
    discount_percent DECIMAL(9,2),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE product (
   id INT AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(100) NOT NULL UNIQUE,
   desc TEXT NOT NULL,
   SKU VARCHAR(100) NOT NULL,
   category_id INT,
   FOREIGN KEY (category_id) REFERENCES product_category (id),
   inventory_id INT UNIQUE,
   FOREIGN KEY (inventory_id) REFERENCES product_inventory (id),
   price DECIMAL(9,2) NOT NULL,
   discount_id INT,
   FOREIGN KEY (discount_id) REFERENCES discount (id),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)